stages:
  evaluate:
    cmd: python src/evaluate.py
    deps:
      - src/evaluate.py
    params:
      - train.learning_rate
      - train.num_epochs
    metrics:
      - log.csv:
          cache: false