stages:
  evaluate:
    cmd: python src/evaluate.py
    deps:
      - src/evaluate.py
    params:
      - train.learning_rate
      - train.num_epochs
    metrics:
      - log.csv:
          cache: false
    plots:
      - classes.csv:
          cache: false
          template: confusion
          x: actual
          y: predicted

  post:
    cmd: python src/post_processing.py
    deps:
      - src/post_processing.py
